[package]
name = "clinews"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.20.0"
dotenv = "0.15.0"
newsapi = {path = "./newsapi"}
termimad = "0.14.2"
